language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-27.0.3
    - android-26

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
