apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: __kaly2.core.STATEFUL_SET_NAME__
spec:
  selector:
    matchLabels:
      app: __kaly2.core.APP_LABEL__
  serviceName: __kaly2.core.SERVICE_NAME__
  replicas: 5
  template:
    metadata:
      labels:
        app: __kaly2.core.APP_LABEL__
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: __kaly2.core.CONTAINER_NAME__
          image: __kaly2.core.IMAGE_NAME__
          ports:
            - containerPort: 9000
